steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/$PROJECT_ID/helloworld-go.$BRANCH_NAME:$BUILD_ID", "-f", "Dockerfile", "."]
images:
- 'gcr.io/$PROJECT_ID/helloworld-go.$BRANCH_NAME:$BUILD_ID'
